DROP TABLE O_TAB_COLUMNS;
CREATE TABLE O_TAB_COLUMNS (
  TABLE_NAME VARCHAR2(30),
  COLUMN_NAME VARCHAR2(30),
  DATA_TYPE VARCHAR2(106),
  DATA_LENGTH NUMBER,
  MAPPING_TYPE VARCHAR2(100),
  MAPPING_VALUE VARCHAR2(255)
);

