DROP TABLE O_TAB_COLUMNS;
CREATE TABLE O_TAB_COLUMNS (
  TABLE_NAME VARCHAR2(30),
  COLUMN_NAME VARCHAR2(30),
  COLUMN_DESCRIPTION VARCHAR2(255),
  COLUMN_ALIGNMENT VARCHAR2(30),
  DATA_TYPE VARCHAR2(100),
  DATA_LENGTH NUMBER,
  REQUIRED VARCHAR2(50)
);

