CREATE OR REPLACE PROCEDURE TRANSFORM_INTERCEPTOR(EVENT VARCHAR2, TABLE_NAME VARCHAR2) AS 
   L_PROCEDURE_EXISTS VARCHAR2(1) := 'Y';
   L_STATEMENT VARCHAR2(1000) := 'BEGIN '||EVENT||'_'||TABLE_NAME||'; END;';
BEGIN 
  SELECT '1' 
  INTO   L_PROCEDURE_EXISTS
  FROM   USER_PROCEDURES
  WHERE  OBJECT_NAME = UPPER(EVENT||'_'||TABLE_NAME);
  
  DBMS_OUTPUT.PUTLINE('TRANSFORM_INTERCEPTOR: '||EVENT||' INVOKING: '||L_STATEMENT);
  EXECUTE IMMEDIATE L_STATEMENT;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUTLINE('TRANSFORM_INTERCEPTOR: '||EVENT||' NO CUSTOM PROCEDURE CREATED FOR TABLE: '||TABLE_NAME);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUTLINE('TRANSFORM_INTERCEPTOR: '||EVENT||' EXCEPTION IN EXECUTING PROCEDURE: '||SQLERRM);
END;
/
