OPERATOR_FOLDER="$PRECISION100_OPERATORS_FOLDER/spool"
PRECISION100_OPERATOR_SPOOL_FOLDER=$PRECISION100_EXECUTION_FOLDER/spool
DEFAULT_QUOTE="OFF"
DEFAULT_DELIMITER=","
DEFAULT_HEADER="OFF"
MARKUP_CSV_SUPPORTED="FALSE"
