PRECISION100_OPERATOR_SMART_MAP_FILE_WORK_FOLDER=$PRECISION100_EXECUTION_FOLDER/smart-map-file/work

MAP_FILE_FILE_SUFFIX="tsv"
MAP_FILE_JOIN_FILTER="__JOIN__"

DEFAULT_TABLE_NAME_PREFIX="O"
DEFAULT_TABLE_NAME_PREFIX="V"
DEFAULT_REVERSE_TABLE_NAME_PREFIX="R"
DEFAULT_TAB_COLUMN_SUFFIX="tab-column"
DEFAULT_TRANSFORM_SUFFIX="transform"
DEFAULT_COLUMN_DATA_TYPE="NVARCHAR2(2000)"

DEFAULT_COLUMN_NAME_INDEX="1"
DEFAULT_OLD_COLUMN_NAME_INDEX="2"
DEFAULT_DATA_TYPE_INDEX="3"
DEFAULT_MAX_LENGTH_INDEX="4"
DEFAULT_MAPPING_TYPE_INDEX="5"
DEFAULT_MAPPING_VALUE_INDEX="6"
#
# To make tab or any non printable character the delimiter use the expression
# 
# export DEFAULT_MAP_FILE_DELIMITER=$'\t'
#
# for others like ',' or '~' etc, we can directly assign the value as below
# export DEFAULT_MAP_FILE_DELIMITER=',' 
#
DEFAULT_MAP_FILE_DELIMITER='~'
