DROP SEQUENCE MASKING_MAPPER_SEQ;
CREATE SEQUENCE MASKING_MAPPER_SEQ START WITH 1000 INCREMENT BY 10 NOCYCLE NOMAXVALUE ORDER CACHE 10;

DROP TABLE MASKING_MAPPER;
CREATE TABLE MASKING_MAPPER(
  SCHEMA_NAME VARCHAR2(255) NOT NULL, 
  TABLE_NAME VARCHAR2(255) NOT NULL, 
  COLUMN_NAME VARCHAR2(255) NOT NULL, 
  PHASE VARCHAR2(255) NOT NULL,
  MASKING_METHOD VARCHAR2(255) NOT NULL, 				
  MASKING_VALUE VARCHAR2(255) NULL, 				
  ENABLED VARCHAR2(10) NOT NULL,
  UPDATE_WHERE VARCHAR2(512)
);
