[ODBC_SPOOL]
[ODBC_SPOOL.ENV]

[ODBC_SPOOL.DEFAULT]
DELIMITER="COMMA"
HEADER="NO"
QUOTE="NO"

[CSV2PARQUET]
[CSV2PARQUET.ENV]

[CSV2PARQUET.DEFAULT]
DELIMITER="COMMA"
HEADER=true
QUOTE="\""
ESCAPE="\\"
IGNORE_ERRORS=true
